{{- $server := required "nfs.server is required" .Values.nfs.server -}}
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: transmission-downloads-nfs
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Delete
  storageClassName: ""
  mountOptions:
    - nfsvers=4.1
  nfs:
    server: {{ $server | quote }}
    path: /mnt/ssd0/downloads
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: transmission-downloads
  namespace: {{ .Release.Namespace }}
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  volumeName: transmission-downloads-nfs
  storageClassName: ""
