apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: transmission-config
  namespace: {{ .Release.Namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.longhorn.configSize }}
  storageClassName: {{ .Values.longhorn.storageClassName | quote }}
