apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: comentario-secrets
  namespace: {{ .Release.Namespace }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: global-secrets
  target:
    name: comentario-secrets
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      data:
        secrets.yaml: |
          sqlite3:
            file: /data/comentario.db
          idp:
            oidc:
              - id: authelia
                name: Authelia
                url: https://auth.ashpex.net
                scopes:
                  - openid
                  - email
                  - profile
                key: {{ "{{ .COMENTARIO_CLIENT_ID }}" }}
                secret: {{ "{{ .COMENTARIO_CLIENT_SECRET }}" }}
  data:
    - secretKey: COMENTARIO_CLIENT_ID
      remoteRef:
        key: oidc.clients
        property: COMENTARIO_CLIENT_ID
    - secretKey: COMENTARIO_CLIENT_SECRET
      remoteRef:
        key: oidc.clients
        property: COMENTARIO_CLIENT_SECRET
