apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: comentario-secrets
  namespace: {{ .Release.Namespace }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: global-secrets
  target:
    name: comentario-secrets
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      data:
        secrets.yaml: |
          sqlite3:
            file: /data/comentario.db
          domainSsoSecret: {{ "{{ .COMENTARIO_CLIENT_SECRET }}" }}
          dynamicConfigDefaults:
            auth:
              signup:
                enableLocal: false
          idps:
            oidc:
              - name: oidc1
                clientId: {{ "{{ .COMENTARIO_CLIENT_ID }}" }}
                clientSecret: {{ "{{ .COMENTARIO_CLIENT_SECRET }}" }}
                authorizeUrl: https://auth.ashpex.net/api/oidc/authorization
                tokenUrl: https://auth.ashpex.net/api/oidc/token
                userInfoUrl: https://auth.ashpex.net/api/oidc/userinfo
  data:
    - secretKey: COMENTARIO_CLIENT_ID
      remoteRef:
        key: oidc.clients
        property: COMENTARIO_CLIENT_ID
    - secretKey: COMENTARIO_CLIENT_SECRET
      remoteRef:
        key: oidc.clients
        property: COMENTARIO_CLIENT_SECRET
