longhorn:
  storageClassName: longhorn
  dataSize: 5Gi

app-template:
  fullnameOverride: comentario
  controllers:
    main:
      containers:
        main:
          image:
            repository: registry.gitlab.com/comentario/comentario
            tag: latest
          probes:
            liveness:
              enabled: false
            readiness:
              enabled: false
            startup:
              enabled: false
          args:
          - --secrets
          - /config/secrets.yaml
          env:
          - name: BASE_URL
            value: https://comments.ashpex.net
          ports:
          - name: http
            containerPort: 80
  service:
    main:
      enabled: true
      controller: main
      type: ClusterIP
      ports:
        http:
          enabled: true
          primary: true
          port: 80
          protocol: HTTP
  ingress:
    main:
      enabled: true
      className: traefik
      annotations: {}
      hosts:
      - host: comments.ashpex.net
        paths:
        - path: "/"
          pathType: Prefix
          service:
            name: main
            port: http
  persistence:
    secrets:
      enabled: true
      type: secret
      name: comentario-secrets
      advancedMounts:
        main:
          main:
          - path: "/config/secrets.yaml"
            subPath: secrets.yaml
            readOnly: true
    data:
      enabled: true
      type: persistentVolumeClaim
      existingClaim: comentario-data
      advancedMounts:
        main:
          main:
          - path: "/data"
