longhorn:
  storageClassName: longhorn
  dataSize: 100Mi

authelia:
  nameOverride: authelia
  pod:
    extraVolumeMounts:
      - name: users-db
        mountPath: /config/users_database.yml
        subPath: users_database.yml
        readOnly: true
      - name: oidc-jwks
        mountPath: /secrets/oidc-jwks
        readOnly: true
    extraVolumes:
      - name: oidc-jwks
        secret:
          secretName: authelia-jwks
          items:
            - key: key.pem
              path: key.pem
      - name: users-db
        configMap:
          name: authelia-users

  ingress:
    enabled: true
    className: traefik
    tls:
      enabled: false

  secret:
    existingSecret: authelia-secrets
    additionalSecrets:
      oidc-clients:
        path: ''

  configMap:
    theme: light

    log:
      level: info

    session:
      cookies:
        - subdomain: auth
          domain: ashpex.net
          default_redirection_url: https://hub.ashpex.net

    storage:
      local:
        enabled: true
        path: /config/db.sqlite3

    authentication_backend:
      file:
        enabled: true
        path: /config/users_database.yml
        password:
          algorithm: argon2

    access_control:
      default_policy: one_factor
      rules:
        - domain: '*.ashpex.net'
          policy: one_factor

    notifier:
      filesystem:
        enabled: true
        filename: /config/notification.txt

    identity_providers:
      oidc:
        enabled: true
        jwks:
          - key_id: default
            key:
              path: '/secrets/oidc-jwks/key.pem'
        lifespans:
          access_token: 1h
          authorize_code: 1m
          id_token: 1h
        claims_policies:
          profile_in_id_token:
            id_token:
              - 'name'
              - 'preferred_username'
              - 'email'
              - 'email_verified'
        clients:
          - client_id: '35ad937b9ec69fcc3a8a747ea18adc6fb95217684e9c65eb0da390bd17e0d18b'
            client_name: 'Forgejo'
            client_secret:
              path: '/secrets/oidc-clients/FORGEJO_CLIENT_SECRET_HASH'
            consent_mode: auto
            public: false
            authorization_policy: one_factor
            require_pkce: true
            pkce_challenge_method: S256
            redirect_uris:
              - https://git.ashpex.net/user/oauth2/authelia/callback
            scopes:
              - openid
              - email
              - profile
              - groups
            response_types:
              - code
            grant_types:
              - authorization_code
            token_endpoint_auth_method: client_secret_basic
          - client_id: 'bdcfd230c7881a386c41df727a048470f8c8b2ac08126e59ce05ee0da39954e5'
            client_name: 'Comentario'
            client_secret:
              path: '/secrets/oidc-clients/COMENTARIO_CLIENT_SECRET_HASH'
            consent_mode: auto
            public: false
            authorization_policy: one_factor
            redirect_uris:
              - https://comments.ashpex.net/api/oauth/oidc:authelia/callback
            scopes:
              - openid
              - email
              - profile
            response_types:
              - code
            grant_types:
              - authorization_code
            token_endpoint_auth_method: client_secret_basic
          - client_id: 'calibre'
            client_name: 'Calibre-Web-Automated'
            client_secret:
              path: '/secrets/oidc-clients/CALIBRE_WEB_CLIENT_SECRET_HASH'
            consent_mode: auto
            public: false
            authorization_policy: one_factor
            require_pkce: false
            pkce_challenge_method: ''
            redirect_uris:
              - https://library.ashpex.net/login/generic/authorized
            scopes:
              - openid
              - email
              - profile
              - groups
            response_types:
              - code
            grant_types:
              - authorization_code
            access_token_signed_response_alg: none
            userinfo_signed_response_alg: none
            token_endpoint_auth_method: client_secret_basic
          - client_id: 'immich'
            client_name: 'Immich'
            client_secret:
              path: '/secrets/oidc-clients/IMMICH_CLIENT_SECRET_HASH'
            consent_mode: auto
            public: false
            authorization_policy: one_factor
            require_pkce: false
            pkce_challenge_method: ''
            redirect_uris:
              - https://photos.ashpex.net/auth/login
              - https://photos.ashpex.net/user-settings
              - app.immich:///oauth-callback
            scopes:
              - openid
              - email
              - profile
            response_types:
              - code
            grant_types:
              - authorization_code
            access_token_signed_response_alg: none
            userinfo_signed_response_alg: none
            token_endpoint_auth_method: client_secret_post
          - client_id: 'romm'
            client_name: 'RomM'
            client_secret:
              path: '/secrets/oidc-clients/ROMM_CLIENT_SECRET_HASH'
            claims_policy: 'profile_in_id_token'
            consent_mode: auto
            public: false
            authorization_policy: one_factor
            require_pkce: false
            pkce_challenge_method: ''
            redirect_uris:
              - https://romm.ashpex.net/api/oauth/openid
            scopes:
              - openid
              - email
              - profile
            response_types:
              - code
            grant_types:
              - authorization_code
            token_endpoint_auth_method: client_secret_basic
          - client_id: 'pingvin-share'
            client_name: 'Pingvin Share'
            client_secret:
              path: '/secrets/oidc-clients/PINGVIN_SHARE_CLIENT_SECRET_HASH'
            claims_policy: 'profile_in_id_token'
            consent_mode: auto
            public: false
            authorization_policy: one_factor
            require_pkce: false
            pkce_challenge_method: ''
            redirect_uris:
              - https://share.ashpex.net/api/oauth/callback/oidc
            scopes:
              - openid
              - email
              - profile
            response_types:
              - code
            grant_types:
              - authorization_code
            token_endpoint_auth_method: client_secret_post

  persistence:
    enabled: true
    existingClaim: authelia-data
