apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: glance-agent
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: glance-agent
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: glance-agent
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: glance-agent
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      containers:
        - name: agent
          image: glanceapp/agent:latest
          imagePullPolicy: Always
          env:
            - name: TZ
              value: Asia/Ho_Chi_Minh
          ports:
            - name: http
              containerPort: 27973
              hostPort: 27973
              protocol: TCP
          securityContext:
            readOnlyRootFilesystem: true
            allowPrivilegeEscalation: false
          resources:
            requests:
              cpu: 10m
              memory: 32Mi
            limits:
              memory: 128Mi
