apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: glance-adguard
  namespace: {{ .Release.Namespace }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: global-secrets
  target:
    name: glance-adguard
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
    - secretKey: username
      remoteRef:
        key: glance.secrets
        property: adguard-username
    - secretKey: password
      remoteRef:
        key: glance.secrets
        property: adguard-password
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: glance-steam
  namespace: {{ .Release.Namespace }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: global-secrets
  target:
    name: glance-steam
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
    - secretKey: api-key
      remoteRef:
        key: glance.secrets
        property: steam-api-key
