---
# Traefik Static Configuration
# Based on best practices from https://doc.traefik.io/traefik/

# API and Dashboard
api:
  dashboard: true
  insecure: true  # WARNING: Only for local/testing - exposes dashboard without auth  

# Entry Points
entryPoints:
  web:
    address: ":80"
    # Redirect all HTTP to HTTPS
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
          permanent: true
    # Trust Cloudflare proxy headers (if behind Cloudflare)
    forwardedHeaders:
      trustedIPs:
        - "173.245.48.0/20"
        - "103.21.244.0/22"
        - "103.22.200.0/22"
        - "103.31.4.0/22"
        - "141.101.64.0/18"
        - "108.162.192.0/18"
        - "190.93.240.0/20"
        - "188.114.96.0/20"
        - "197.234.240.0/22"
        - "198.41.128.0/17"
        - "162.158.0.0/15"
        - "104.16.0.0/13"
        - "104.24.0.0/14"
        - "172.64.0.0/13"
        - "131.0.72.0/22"
  
  websecure:
    address: ":443"
    http:
      tls:
        certResolver: letsencrypt
        options: default
      # Add security headers at entry point level
      middlewares:
        - secure-headers@file
  
  # Health check endpoint
  traefik:
    address: ":8082"

# Docker Provider
providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false  # Only expose containers with traefik.enable=true
    network: "{{ docker_network }}"
  
  file:
    directory: "/dynamic"
    watch: true

# TLS Configuration
tls:
  options:
    default:
      minVersion: VersionTLS12
      cipherSuites:
        - TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
        - TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
        - TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305
        - TLS_AES_128_GCM_SHA256
        - TLS_AES_256_GCM_SHA384
        - TLS_CHACHA20_POLY1305_SHA256
      sniStrict: true

# Certificate Resolvers (Let's Encrypt)
certificatesResolvers:
  letsencrypt:
    acme:
      email: "{{ services.traefik.acme_email }}"
      storage: /acme.json
      # Use HTTP challenge for certificate validation
      httpChallenge:
        entryPoint: web
      # Uncomment for staging/testing to avoid rate limits
      # caServer: "https://acme-staging-v02.api.letsencrypt.org/directory"

# Ping / Health Check
ping:
  entryPoint: traefik

# Global Configuration
global:
  checkNewVersion: true
  sendAnonymousUsage: false

