nfs:
  server: 192.168.1.110

longhorn:
  storageClassName: longhorn
  configSize: 100Mi

app-template:
  fullnameOverride: radarr
  controllers:
    main:
      containers:
        main:
          image:
            repository: lscr.io/linuxserver/radarr
            tag: latest
          probes:
            liveness:
              enabled: false
            readiness:
              enabled: false
            startup:
              enabled: false
          env:
          - name: PUID
            value: '1000'
          - name: PGID
            value: '1000'
          - name: TZ
            value: Asia/Ho_Chi_Minh
          ports:
          - name: web
            containerPort: 7878
  service:
    main:
      enabled: true
      controller: main
      type: ClusterIP
      ports:
        web:
          enabled: true
          primary: true
          port: 7878
          protocol: HTTP
  ingress:
    main:
      enabled: true
      className: traefik
      annotations: {}
      hosts:
      - host: radarr.ashpex.net
        paths:
        - path: "/"
          pathType: Prefix
          service:
            identifier: main
            port: web
  persistence:
    main-config:
      enabled: true
      type: persistentVolumeClaim
      existingClaim: radarr-config
      advancedMounts:
        main:
          main:
          - path: "/config"
    main-logs:
      enabled: true
      type: emptyDir
      advancedMounts:
        main:
          main:
          - path: "/config/logs"
    main-movies:
      enabled: true
      type: persistentVolumeClaim
      existingClaim: radarr-movies
      advancedMounts:
        main:
          main:
          - path: "/movies"
    main-downloads:
      enabled: true
      type: persistentVolumeClaim
      existingClaim: radarr-downloads
      advancedMounts:
        main:
          main:
          - path: "/downloads"
