{{- $server := required "nfs.server is required" .Values.nfs.server -}}
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: frigate-media-nfs
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  mountOptions:
    - nfsvers=4.1
  nfs:
    server: {{ $server | quote }}
    path: /mnt/ssd0/nvr/frigate
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: frigate-media
  namespace: {{ .Release.Namespace }}
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  volumeName: frigate-media-nfs
  storageClassName: ""
