apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: pingvin-share-config
  namespace: {{ .Release.Namespace }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: global-secrets
  target:
    creationPolicy: Owner
    deletionPolicy: Retain
    name: pingvin-share-config
    template:
      engineVersion: v2
      mergePolicy: Replace
      data:
        config.yaml: |
          general:
            appName: Ashpex's Share
            appUrl: https://share.ashpex.net
            secureCookies: "true"
            showHomePage: "false"
            sessionDuration: 3 months
          share:
            allowRegistration: "false"
            allowUnauthenticatedShares: "false"
            maxExpiration: 0 days
            maxSize: "5000000000"
            chunkSize: "10000000"
          oauth:
            allowRegistration: "true"
            ignoreTotp: "true"
            disablePassword: "true"
            oidc-enabled: "true"
            oidc-discoveryUri: https://auth.ashpex.net/.well-known/openid-configuration
            oidc-signOut: "true"
            oidc-scope: openid email profile
            oidc-clientId: "pingvin-share"
            oidc-clientSecret: "{{`{{ .PINGVIN_SHARE_CLIENT_SECRET }}`}}"
          initUser:
            enabled: false
  data:
    - secretKey: PINGVIN_SHARE_CLIENT_SECRET
      remoteRef:
        key: oidc.clients
        property: PINGVIN_SHARE_CLIENT_SECRET
