apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: authelia-secrets
  namespace: {{ .Release.Namespace }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: global-secrets
  target:
    name: authelia-secrets
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      data:
        identity_validation.jwt.key: "{{ "{{ .AUTHELIA_JWT_SECRET }}" }}"
        session.key: "{{ "{{ .AUTHELIA_SESSION_SECRET }}" }}"
        storage.key: "{{ "{{ .AUTHELIA_STORAGE_KEY }}" }}"
        identity_providers.oidc.hmac.key: "{{ "{{ .AUTHELIA_SESSION_SECRET }}" }}"
        oidc-jwks.pem: "{{ "{{ .AUTHELIA_OIDC_JWKS_KEY | base64decode }}" }}"
  data:
    - secretKey: AUTHELIA_JWT_SECRET
      remoteRef:
        key: authelia.secrets
        property: AUTHELIA_JWT_SECRET
    - secretKey: AUTHELIA_SESSION_SECRET
      remoteRef:
        key: authelia.secrets
        property: AUTHELIA_SESSION_SECRET
    - secretKey: AUTHELIA_STORAGE_KEY
      remoteRef:
        key: authelia.secrets
        property: AUTHELIA_STORAGE_KEY
    - secretKey: AUTHELIA_OIDC_JWKS_KEY
      remoteRef:
        key: authelia.secrets
        property: AUTHELIA_OIDC_JWKS_KEY
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: oidc-clients
  namespace: {{ .Release.Namespace }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: global-secrets
  target:
    creationPolicy: Owner
    deletionPolicy: Retain
  dataFrom:
    - extract:
        key: oidc.clients
