apiVersion: v1
kind: ConfigMap
metadata:
  name: authelia-users
  namespace: {{ .Release.Namespace }}
data:
  users_database.yml: |
    users:
      ashpex:
        displayname: "Ashpex"
        password: "$argon2id$v=19$m=65536,t=3,p=4$dzd7vY8OgmK8/QqID5gbjA$LvQdiklyS1AeGvLJqUqUnm6Jy1Nb4nKJAOrJAVcQuQw"
        email: "ashpex@pm.me"
        groups:
          - admins
