apiVersion: v1
kind: ConfigMap
metadata:
  name: authelia-users
  namespace: {{ .Release.Namespace }}
data:
  users_database.yml: |
    users:
      ashpex:
        displayname: "Ashpex"
        password: "$argon2id$v=19$m=65536,t=3,p=4$VroCi4ZzfEPs1m5RSH2Ryg$1A0jCBj0Iu+a8SPLpXGmx4lVKaxSMmw3uGA5tmVuWkY"
        email: "ashpex@pm.me"
        groups:
          - admins
