nfs:
  server: 192.168.1.110

longhorn:
  storageClassName: longhorn
  dataSize: 100Mi

pluginDownload:
  enabled: false

app-template:
  fullnameOverride: navidrome
  controllers:
    main:
      containers:
        main:
          image:
            repository: deluan/navidrome
            tag: latest
          probes:
            liveness:
              enabled: false
            readiness:
              enabled: false
            startup:
              enabled: false
          env:
          - name: TZ
            value: Asia/Ho_Chi_Minh
          - name: ND_MUSICFOLDER
            value: /music
          - name: ND_DATAFOLDER
            value: /data
          - name: ND_BASEURL
            value: https://music.ashpex.net
          - name: ND_PLUGINS_ENABLED
            value: "true"
          - name: ND_PLUGINS_FOLDER
            value: /data/plugins
          - name: ND_LYRICSPRIORITY
            value: ".lrc,nd-lyrics"
          ports:
          - name: http
            containerPort: 4533
  service:
    main:
      enabled: true
      controller: main
      type: ClusterIP
      ports:
        http:
          enabled: true
          primary: true
          port: 4533
          protocol: HTTP
  ingress:
    main:
      enabled: true
      className: traefik
      annotations: {}
      hosts:
      - host: music.ashpex.net
        paths:
        - path: "/"
          pathType: Prefix
          service:
            identifier: main
            port: http
  persistence:
    data:
      enabled: true
      type: persistentVolumeClaim
      existingClaim: navidrome-data
      advancedMounts:
        main:
          main:
          - path: "/data"
    music:
      enabled: true
      type: persistentVolumeClaim
      existingClaim: navidrome-music
      advancedMounts:
        main:
          main:
          - path: "/music"
