---
# Service configurations with ports and settings
services:
  adguard:
    enabled:  true 
    web_port: 8081 
    dns_port: 53
    data_path: "{{ base_data_path }}/adguard"
    domain: "adguard.ashpex.net"
    dns_domain: "dns.ashpex.net"  # For DNS-over-HTTPS
    
  alist:
    enabled: true 
    port: 8083  # External port mapping
    data_path: "{{ base_data_path }}/alist"
    domain: "files.ashpex.net"
    
  arr:
    enabled: false
    data_path: "{{ base_data_path }}/arr"
    sonarr_port: 8989
    radarr_port: 7878
    prowlarr_port: 9696
    
  audiobookshelf:
    enabled: true 
    port: 13378
    config_path: "{{ base_data_path }}/audiobookshelf/config"
    metadata_path: "{{ base_data_path }}/audiobookshelf/metadata"
    data_path: "{{ media_path }}/library"
    domain: "library.ashpex.net"
    
  backrest:
    enabled: false 
    port: 9898
    data_path: "{{ base_data_path }}/backrest/data"
    config_path: "{{ base_data_path }}/backrest/config"
    cache_path: "{{ base_data_path }}/backrest/cache"
    
  copyparty:
    enabled: true 
    port: 3923
    config_path: "{{ base_data_path }}/copyparty/config"
    share_path: "{{ root_path }}"
    username: "{{ vault_copyparty_username }}"
    password: "{{ vault_copyparty_password }}"
    domain: "share.ashpex.net"
    
  frigate:
    enabled: false 
    web_port: 8971
    rtsp_port: 8554
    webrtc_tcp_port: 8555
    webrtc_udp_port: 8555
    config_path: "{{ base_data_path }}/frigate"
    data_path: "{{ nvr_path }}/frigate"
    shm_size: "100mb"
    domain: "camera.ashpex.net"
    
  glance:
    enabled: true
    port: 8090  # Changed from 80 to avoid conflict with Traefik
    config_path: "{{ base_data_path }}/glance/config"
    domain: "hub.ashpex.net"
    
  gotify:
    enabled: true 
    port: 8888
    data_path: "{{ base_data_path }}/gotify"
    domain: "gotify.ashpex.net"
    
  immich:
    enabled: true 
    port: 2283
    upload_path: "{{ media_path }}/immich"
    data_path: "{{ base_data_path }}/immich"
    db_password: "{{ vault_immich_db_password | default('changeme') }}"
    db_username: "immich"
    db_name: "immich"
    version: "release"
    domain: "photos.ashpex.net"
    
  jellyfin:
    enabled: true 
    web_port: 8096  # Web interface port
    network_mode: "host"
    memory_limit: "1g"
    config_path: "{{ base_data_path }}/jellyfin/config"
    cache_path: "{{ base_data_path }}/jellyfin/cache"
    media_path: "{{ media_path }}"
    domain: "media.ashpex.net"
    
  qbittorrent:
    enabled: true 
    web_port: 8084
    torrent_port: 6881
    config_path: "{{ base_data_path }}/qbittorrent"
    downloads_path: "{{ downloads_path }}"
    domain: "torrent.ashpex.net"
    
  romm:
    enabled: true 
    web_port: 8086
    library_path: "{{ media_path }}/games"    # ROM library structure: /roms/{platform}/ and /bios/{platform}/
    assets_path: "{{ base_data_path }}/romm/assets"     # Saves, states, etc.
    config_path: "{{ base_data_path }}/romm/config"     # config.yml location  
    db_name: "romm"
    db_user: "romm-user"
    # Sensitive data in vault.yml:
    # romm_db_password, romm_db_root_password, romm_auth_secret_key
    # romm_igdb_client_id, romm_igdb_client_secret
    domain: "romm.ashpex.net"
    
  waline:
    enabled: true 
    port: 8360
    data_path: "{{ base_data_path }}/waline"
    domain: "comments.ashpex.net"
    
  authelia:
    enabled: true
    web_port: 9091
    domain: "auth.ashpex.net"
    data_path: "{{ base_data_path }}/authelia"
    config_path: "{{ base_data_path }}/authelia/config"
    jwt_secret: "{{ vault_authelia_jwt_secret }}"
    session_secret: "{{ vault_authelia_session_secret }}"
    storage_encryption_key: "{{ vault_authelia_storage_key }}"
    default_redirect_url: "https://hub.ashpex.net"
    theme: "light"
    # OIDC client for Forgejo
    forgejo_client_id: "{{ vault_authelia_forgejo_client_id | default('') }}"
    forgejo_client_secret_hash: "{{ vault_authelia_forgejo_client_secret_hash | default('') }}"
    forgejo_auth_name: "authelia"
    
  watchtower:
    enabled: true 
    web_port: 8085  # Optional web interface
    
  forgejo:
    enabled: true
    web_port: 8087  # External port mapping
    data_path: "{{ base_data_path }}/forgejo"
    domain: "git.ashpex.net"
    
  traefik:
    enabled: true
    web_port: 80        # HTTP
    websecure_port: 443 # HTTPS
    dashboard_port: 8080 # Dashboard/API
    health_port: 8082   # Health check endpoint
    data_path: "{{ base_data_path }}/traefik"
    config_path: "{{ base_data_path }}/traefik/config"
    # Domain for the dashboard (optional)
    dashboard_domain: "traefik.ashpex.net"
    # Email for Let's Encrypt certificates
    acme_email: "{{ vault_acme_email }}"