app-template:
  fullnameOverride: romm
  controllers:
    app:
      containers:
        main:
          image:
            repository: rommapp/romm
            tag: latest
          probes:
            liveness:
              enabled: false
            readiness:
              enabled: false
            startup:
              enabled: false
          env:
          - name: DB_HOST
            value: romm-db
          - name: DB_NAME
            value: romm
          - name: DB_USER
            value: romm-user
          - name: DB_PASSWD
            valueFrom:
              secretKeyRef:
                name: romm-secrets
                key: DB_PASSWD
          - name: ROMM_AUTH_SECRET_KEY
            valueFrom:
              secretKeyRef:
                name: romm-secrets
                key: ROMM_AUTH_SECRET_KEY
          - name: IGDB_CLIENT_ID
            valueFrom:
              secretKeyRef:
                name: romm-secrets
                key: IGDB_CLIENT_ID
          - name: IGDB_CLIENT_SECRET
            valueFrom:
              secretKeyRef:
                name: romm-secrets
                key: IGDB_CLIENT_SECRET
          - name: PLAYMATCH_API_ENABLED
            value: 'true'
          - name: RETROACHIEVEMENTS_API_KEY
            valueFrom:
              secretKeyRef:
                name: romm-secrets
                key: RETROACHIEVEMENTS_API_KEY
          - name: ENABLE_SCHEDULED_RESCAN
            value: 'true'
          - name: SCHEDULED_RESCAN_CRON
            value: 0 3 * * *
          - name: ENABLE_SCHEDULED_UPDATE_SWITCH_TITLEDB
            value: 'true'
          - name: SCHEDULED_UPDATE_SWITCH_TITLEDB_CRON
            value: 0 4 * * *
          - name: ENABLE_RESCAN_ON_FILESYSTEM_CHANGE
            value: 'true'
          - name: RESCAN_ON_FILESYSTEM_CHANGE_DELAY
            value: '5'
          ports:
          - name: http
            containerPort: 8080
    database:
      containers:
        main:
          image:
            repository: mariadb
            tag: latest
          probes:
            liveness:
              enabled: false
            readiness:
              enabled: true
              custom: true
              spec:
                tcpSocket:
                  port: mysql
                initialDelaySeconds: 30
                periodSeconds: 10
            startup:
              enabled: false
          env:
          - name: MARIADB_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: romm-secrets
                key: MARIADB_ROOT_PASSWORD
          - name: MARIADB_DATABASE
            value: romm
          - name: MARIADB_USER
            value: romm-user
          - name: MARIADB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: romm-secrets
                key: DB_PASSWD
          ports:
          - name: mysql
            containerPort: 3306
    main:
      enabled: false
  service:
    main:
      enabled: true
      controller: app
      type: ClusterIP
      ports:
        http:
          enabled: true
          primary: true
          port: 8080
          protocol: HTTP
    db:
      enabled: true
      controller: database
      type: ClusterIP
      ports:
        mysql:
          enabled: true
          primary: true
          port: 3306
          protocol: TCP
        http:
          enabled: false
  ingress:
    main:
      enabled: true
      className: traefik
      annotations: {}
      hosts:
      - host: romm.ashpex.net
        paths:
        - path: "/"
          pathType: Prefix
          service:
            name: main
            port: http
  persistence:
    app-resources:
      enabled: true
      type: hostPath
      hostPath: "/mnt/hdd1/infra-data/romm/resources"
      hostPathType: DirectoryOrCreate
      advancedMounts:
        app:
          main:
          - path: "/romm/resources"
    app-redis-data:
      enabled: true
      type: hostPath
      hostPath: "/mnt/hdd1/infra-data/romm/redis"
      hostPathType: DirectoryOrCreate
      advancedMounts:
        app:
          main:
          - path: "/redis-data"
    app-library:
      enabled: true
      type: hostPath
      hostPath: "/mnt/hdd1/media/games"
      hostPathType: Directory
      advancedMounts:
        app:
          main:
          - path: "/romm/library"
    app-assets:
      enabled: true
      type: hostPath
      hostPath: "/mnt/hdd1/infra-data/romm/assets"
      hostPathType: Directory
      advancedMounts:
        app:
          main:
          - path: "/romm/assets"
    app-config:
      enabled: true
      type: hostPath
      hostPath: "/mnt/hdd1/infra-data/romm/config"
      hostPathType: Directory
      advancedMounts:
        app:
          main:
          - path: "/romm/config"
    app-timezone:
      enabled: true
      type: hostPath
      hostPath: "/etc/timezone"
      hostPathType: File
      advancedMounts:
        app:
          main:
          - path: "/etc/timezone"
            readOnly: true
    app-localtime:
      enabled: true
      type: hostPath
      hostPath: "/etc/localtime"
      hostPathType: File
      advancedMounts:
        app:
          main:
          - path: "/etc/localtime"
            readOnly: true
    database-mysql-data:
      enabled: true
      type: hostPath
      hostPath: "/mnt/hdd1/infra-data/romm/mysql"
      hostPathType: DirectoryOrCreate
      advancedMounts:
        database:
          main:
          - path: "/var/lib/mysql"
