apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: traefik
  namespace: flux-system
spec:
  targetNamespace: traefik
  interval: 30m
  chart:
    spec:
      chart: ./platform/traefik
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
      interval: 12h
      reconcileStrategy: Revision
  maxHistory: 2
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
