nfs:
  server: 192.168.1.110

app-template:
  fullnameOverride: transmission
  controllers:
    main:
      containers:
        main:
          image:
            repository: lscr.io/linuxserver/transmission
            tag: latest
          probes:
            liveness:
              enabled: false
            readiness:
              enabled: false
            startup:
              enabled: false
          env:
          - name: PUID
            value: '1000'
          - name: PGID
            value: '1000'
          - name: TZ
            value: Asia/Ho_Chi_Minh
          - name: PEERPORT
            value: '51413'
          ports:
          - name: web
            containerPort: 9091
          - name: torrent-tcp
            containerPort: 51413
            protocol: TCP
            hostPort: 51413
          - name: torrent-udp
            containerPort: 51413
            protocol: UDP
            hostPort: 51413
  service:
    main:
      enabled: true
      controller: main
      type: ClusterIP
      ports:
        web:
          enabled: true
          primary: true
          port: 9091
          protocol: HTTP
        torrent-tcp:
          enabled: true
          primary: false
          port: 51413
          protocol: TCP
        torrent-udp:
          enabled: true
          primary: false
          port: 51413
          protocol: UDP
  ingress:
    main:
      enabled: true
      className: traefik
      annotations: {}
      hosts:
      - host: torrent.ashpex.net
        paths:
        - path: "/"
          pathType: Prefix
          service:
            identifier: main
            port: web
  persistence:
    main-config:
      enabled: true
      type: hostPath
      hostPath: "/mnt/hdd1/infra-data/transmission"
      hostPathType: DirectoryOrCreate
      advancedMounts:
        main:
          main:
          - path: "/config"
    main-downloads:
      enabled: true
      type: persistentVolumeClaim
      existingClaim: transmission-downloads
      advancedMounts:
        main:
          main:
          - path: "/downloads"
