apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - traefik/release.yaml
  - external-secrets/release.yaml
  - local-storage/release.yaml
  - global-secrets/release.yaml
  - cert-manager/release.yaml
  - cert-manager-config/release.yaml
