name: hdd-local
isDefaultClass: false
provisioner: rancher.io/local-path
nodePath: /mnt/ssd0/k8s-volumes
pathPattern: "{{ .PVC.Namespace }}/{{ .PVC.Name }}"
volumeBindingMode: WaitForFirstConsumer
reclaimPolicy: Retain
allowVolumeExpansion: true
