apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: immich-db
  namespace: {{ .Release.Namespace }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: global-secrets
  target:
    creationPolicy: Owner
    deletionPolicy: Retain
  dataFrom:
    - extract:
        key: immich.db
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: immich-config
  namespace: {{ .Release.Namespace }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: global-secrets
  target:
    name: immich-config
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      data:
        immich.yaml: |
          backup:
            database:
              keepLastAmount: 3
          machineLearning:
            enabled: false
          oauth:
            enabled: true
            issuerUrl: https://auth.ashpex.net/.well-known/openid-configuration
            clientId: "{{ "{{ .IMMICH_CLIENT_ID }}" }}"
            clientSecret: "{{ "{{ .IMMICH_CLIENT_SECRET }}" }}"
            scope: openid email profile
            buttonText: Login with Authelia
            autoRegister: false
            autoLaunch: false
            tokenEndpointAuthMethod: client_secret_post
            signingAlgorithm: RS256
            profileSigningAlgorithm: none
          passwordLogin:
            enabled: true
  data:
    - secretKey: IMMICH_CLIENT_ID
      remoteRef:
        key: oidc.clients
        property: IMMICH_CLIENT_ID
    - secretKey: IMMICH_CLIENT_SECRET
      remoteRef:
        key: oidc.clients
        property: IMMICH_CLIENT_SECRET
