apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: immich-postgres
  namespace: {{ .Release.Namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.longhorn.postgresSize }}
  storageClassName: {{ .Values.longhorn.storageClassName | quote }}
