app-template:
  fullnameOverride: waline
  controllers:
    main:
      containers:
        main:
          image:
            repository: lizheming/waline
            tag: latest
          probes:
            liveness:
              enabled: false
            readiness:
              enabled: false
            startup:
              enabled: false
          env:
          - name: TZ
            value: Asia/Ho_Chi_Minh
          - name: SQLITE_PATH
            value: "/app/data"
          - name: JWT_TOKEN
            valueFrom:
              secretKeyRef:
                name: waline-secrets
                key: JWT_TOKEN
          - name: SITE_NAME
            valueFrom:
              secretKeyRef:
                name: waline-secrets
                key: SITE_NAME
          - name: SITE_URL
            valueFrom:
              secretKeyRef:
                name: waline-secrets
                key: SITE_URL
          - name: SECURE_DOMAINS
            valueFrom:
              secretKeyRef:
                name: waline-secrets
                key: SECURE_DOMAINS
          - name: AUTHOR_EMAIL
            valueFrom:
              secretKeyRef:
                name: waline-secrets
                key: AUTHOR_EMAIL
          ports:
          - name: http
            containerPort: 8360
  service:
    main:
      enabled: true
      controller: main
      type: ClusterIP
      ports:
        http:
          enabled: true
          primary: true
          port: 8360
          protocol: HTTP
  ingress:
    main:
      enabled: true
      className: traefik
      annotations: {}
      hosts:
      - host: comments.ashpex.net
        paths:
        - path: "/"
          pathType: Prefix
          service:
            name: main
            port: http
  persistence:
    main-data:
      enabled: true
      type: hostPath
      hostPath: "/mnt/hdd1/infra-data/waline"
      hostPathType: Directory
      advancedMounts:
        main:
          main:
          - path: "/app/data"
