apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: romm-secrets
  namespace: {{ .Release.Namespace }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: global-secrets
  target:
    creationPolicy: Owner
    deletionPolicy: Retain
    name: romm-secrets
  data:
    - secretKey: ROMM_DB_PASSWORD
      remoteRef:
        key: romm.secrets
        property: ROMM_DB_PASSWORD
    - secretKey: ROMM_AUTH_SECRET_KEY
      remoteRef:
        key: romm.secrets
        property: ROMM_AUTH_SECRET_KEY
    - secretKey: ROMM_CLIENT_SECRET
      remoteRef:
        key: oidc.clients
        property: ROMM_CLIENT_SECRET
