nfs:
  server: 192.168.1.110

app-template:
  fullnameOverride: frigate
  controllers:
    main:
      containers:
        main:
          image:
            repository: ghcr.io/blakeblackshear/frigate
            tag: stable
          probes:
            liveness:
              enabled: false
            readiness:
              enabled: false
            startup:
              enabled: false
          env:
          - name: TZ
            value: Asia/Ho_Chi_Minh
          securityContext:
            privileged: true
          ports:
          - name: http
            containerPort: 8971
          - name: rtsp
            containerPort: 8554
            protocol: TCP
          - name: webrtc-tcp
            containerPort: 8555
            protocol: TCP
          - name: webrtc-udp
            containerPort: 8555
            protocol: UDP
      pod:
        securityContext: {}
  service:
    main:
      enabled: true
      controller: main
      type: ClusterIP
      ports:
        http:
          enabled: true
          primary: true
          port: 8971
          protocol: HTTP
  ingress:
    main:
      enabled: true
      className: traefik
      annotations: {}
      hosts:
      - host: nvr.ashpex.net
        paths:
        - path: "/"
          pathType: Prefix
          service:
            name: main
            port: http
  persistence:
    main-config:
      enabled: true
      type: hostPath
      hostPath: "/mnt/hdd1/infra-data/frigate"
      hostPathType: Directory
      advancedMounts:
        main:
          main:
          - path: "/config"
    main-media:
      enabled: true
      type: persistentVolumeClaim
      existingClaim: frigate-media
      advancedMounts:
        main:
          main:
          - path: "/media/frigate"
    main-cache:
      enabled: true
      type: emptyDir
      sizeLimit: 250Mi
      advancedMounts:
        main:
          main:
          - path: "/tmp/cache"
    main-shm:
      enabled: true
      type: emptyDir
      medium: Memory
      sizeLimit: 100Mi
      advancedMounts:
        main:
          main:
          - path: "/dev/shm"
    main-localtime:
      enabled: true
      type: hostPath
      hostPath: "/etc/localtime"
      hostPathType: File
      advancedMounts:
        main:
          main:
          - path: "/etc/localtime"
            readOnly: true
