apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - adguard/release.yaml
  - backrest/release.yaml
  - authelia/release.yaml
  - copyparty/release.yaml
  - forgejo/release.yaml
  - frigate/release.yaml
  - glance/release.yaml
  - ntfy/release.yaml
  - immich/release.yaml
  - immich-public-proxy/release.yaml
  - navidrome/release.yaml
  - transmission/release.yaml
  - comentario/release.yaml
  - romm/release.yaml
  - calibre-web/release.yaml
