apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: forgejo-admin
  namespace: {{ .Release.Namespace }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: global-secrets
  target:
    name: forgejo-admin
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      data:
        username: ashpex
        password: "{{ "{{ .ADMIN_PASSWORD }}" }}"
        email: ashpex@pm.me
  data:
    - secretKey: ADMIN_PASSWORD
      remoteRef:
        key: forgejo.secrets
        property: ADMIN_PASSWORD
