apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: forgejo-oauth
  namespace: {{ .Release.Namespace }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: global-secrets
  target:
    name: forgejo-oauth
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      data:
        key: "{{ "{{ .FORGEJO_CLIENT_ID }}" }}"
        secret: "{{ "{{ .FORGEJO_CLIENT_SECRET }}" }}"
  data:
    - secretKey: FORGEJO_CLIENT_ID
      remoteRef:
        key: oidc.clients
        property: FORGEJO_CLIENT_ID
    - secretKey: FORGEJO_CLIENT_SECRET
      remoteRef:
        key: oidc.clients
        property: FORGEJO_CLIENT_SECRET
