---
- name: Stop Homeserver Services
  hosts: homeserver
  gather_facts: no
  vars_files:
    - ../group_vars/all/services.yml
    - ../group_vars/all/vault.yml

  tasks:
    - name: Stop enabled services via role
      include_role:
        name: service
      vars:
        service_key: "{{ item.key }}"
        service_cfg: "{{ item.value }}"
        service_action: down
      when: item.value.enabled | default(false)
      loop: "{{ services | dict2items }}"
      loop_control:
        label: "{{ item.key }}"

    - name: Display stop status
      debug:
        msg: "🛑 All enabled services have been stopped."
