---
- name: Update Homeserver Services
  hosts: homeserver
  gather_facts: no
  vars_files:
    - ../group_vars/all/services.yml
    - ../group_vars/all/vault.yml

  tasks:
    - name: Pull images for enabled services via role
      include_role:
        name: service
      vars:
        service_key: "{{ item.key }}"
        service_cfg: "{{ item.value }}"
        service_action: pull
      when: item.value.enabled | default(false)
      loop: "{{ services | dict2items }}"
      loop_control:
        label: "{{ item.key }}"

    - name: Recreate containers for enabled services via role
      include_role:
        name: service
      vars:
        service_key: "{{ item.key }}"
        service_cfg: "{{ item.value }}"
        service_action: recreate
      when: item.value.enabled | default(false)
      loop: "{{ services | dict2items }}"
      loop_control:
        label: "{{ item.key }}"

    - name: Clean up old images
      command: docker image prune -f

    - name: Display update status
      debug:
        msg: "✅ Update cycle completed (pull + recreate)."
